[package]
name = "fhn"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
rand = "0.8"
rand_distr = "0.4"
nalgebra = "0.32"
plotters = "0.3"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
clap = { version= "4", features = ["derive"] }
